##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190425       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190425-dmr_plots.Rmd")' 2> log >> log
