##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190315       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190315-dmrseq.Rmd")' 2> log >> log
